### ISSUE TITLE
Unable to effectively prevent occlusion

### ISSUE THREAD

**Issue by zh-csc** [markisus/pytagmapper#3]
Hello, I am using your project in Inside_ Out_ In the tracker file, my occlusion has a significant impact on him. As long as it is occluded, it cannot be detected. I request your help

**Comment by markisus** [comment]
Can you upload a screen recording of the effect? You can drag and drop a video file into your reply on this issue, or upload to imgur.com.

**Comment by zh-csc** [comment]
Thank you for your response！https://1drv.ms/b/s!Am34rxOMkDUNejQQ2uN84bgjs10?e=8nrqab ，https://1drv.ms/v/s!Am34rxOMkDUNeRRcAraMjMsMJHs?e=eAgDdf

**Comment by markisus** [comment]
When I look at your video, it's apparent that the tracker never initializes properly. That's why there are a cluster of tags right in the middle of the screen. 
![image](https://github.com/markisus/pytagmapper/assets/469689/9323aaec-8955-4f68-8e38-09539cbabc90)

When working properly, each tag in this cluster moves towards its correct location. Additionally you can tell by the huge tracking error that the program has not successfully figured out where the camera is.

![image](https://github.com/markisus/pytagmapper/assets/469689/1b4f9cbe-5cb8-43df-97b2-e57b340f9961)

Have you checked that the map that was built (try `python pytagmapper_tools/show_map.py [the map directory]`) matches what you see in real life? Please paste a screenshot.

Also it looks like your setup is 2D, so you should use `--mode 2d`  when you run `build_map.py`.

**Comment by markisus** [comment]
@zh-csc Any updates?

**Comment by zh-csc** [comment]
I'm not sure where my problem lies, but I now suspect it's an initialization issue (referencing your other issue, which was shot with an iPhone, and I suspect the iPhone's lens zooming may result in inaccurate camera parameters). My issue is similar, and I suspect it's a distortion or camera parameter problem. However, even after changing the camera, there hasn't been much improvement.Finally, thank you for your patient replies and assistance. Best wishes!

**Comment by markisus** [comment]
No problem! In the other issue, the user mentioned some alternative software that ended up working well for him. I encourage you to try that as well.
